### ISSUE TITLE
Environmental Variable Naming - Failing to import mujoco-py  

### ISSUE THREAD

**Issue by huanntran100** [openai/mujoco-py#167]
The process for installing this package is supposed to be straightforward, but I am not really sure what's going on with this environmental naming error that keeps popping up no matter what I try. I have scoured every thread that mentions any of this to address this issue, so any help would be greatly appreciated.

Basically, mujoco-py failed to import inside my python notebook raising the following error: 

![image](https://user-images.githubusercontent.com/32233994/32681291-a8209376-c623-11e7-85ad-56b61ac02cae.png)

I have successfully installed mujoco-py on Windows 10 64-bit using pip install as instructed, and I am currently on Python 3 64-bit. 

Here are my mjpro131 binaries and activation key text file inside my .mujoco folder: 

![image](https://user-images.githubusercontent.com/32233994/32681223-3e3c1c00-c623-11e7-99ce-a71924598ee2.png)

Here's how I set my environmental variables, which I directly got from browsing the directory/file for the path names: 

![image](https://user-images.githubusercontent.com/32233994/32681176-fff91f42-c622-11e7-8c1a-99bc2aff1ce0.png)

**Comment by huanntran95** [comment]
Okay so after like a few days of not knowing what was going on or how to fix this, I just uninstalled mujoco-py and deleted every mujoco binary file on my computer and started over from scratch. To be honest, I just redid the steps exactly as shown on the github and made a few small changes to the site-package files based on other solutions I found online. Here are the steps I took to fix the problem: 

System:
- Windows 10 64-bit
- Python 3.5 64-bit

1) **pip install mujoco-py == 0.5.7** 
2) made a **.mujoco directory** inside my user folder, which is "Steven Tran" in my case. 
3) extracted my **mjpro131 binary folder** into the **.mujoco directory**
4) put my license key **mjkey.txt** into **.mujoco directory**
- I didn't run into any weird environmental path naming error this time so not really sure what I did right this time. 

5) in **mujoco_py/mjlib.py**, changed bin/mujoco131.**lib** --> bin/mujoco131.**dll** 
- This was because  "[Win 193] %1 is not a valid win32 application" 

6) in **mujoco_py/platname_targdir.py**, changed sys.platform.startswith("**windows**") --> sys.platform.startswith("**win**")
- This was because for some odd reason, "windows" is not recognized but "win" is. 

Steps 1) to 4) are as shown in the mujoco_py github: https://github.com/openai/mujoco-py
Step 5) was found here: https://github.com/openai/mujoco-py/issues/83 
Step 6) was found here although the pull request was for the : https://github.com/openai/mujoco-py/pull/37/files 

Anyway, here's proof that it works now: 
![image](https://user-images.githubusercontent.com/32233994/32715335-c3e3a776-c806-11e7-9f6d-fcf5d4bf2acc.png)

Hopefully, this helps anyone with similar issues. Obviously, this problem has been addressed before, but I think it helps for people to see multiple instances of a problem being addressed.
