### ISSUE TITLE
How to capture specific figures from Mujoco

### ISSUE THREAD

**Issue by JackieTseng** [openai/mujoco-py#279]
Hey, I want to take some screenshot in mujoco_env under condition of:
* removing the grid in mujoco env
* assigning a specific and nice pose in the simulator, if possible

An example like this:
![screenshot from 2018-08-25 09-53-41](https://user-images.githubusercontent.com/7310697/44613866-0420b280-a84d-11e8-9056-f184625bfd95.png)
Any ideas? THX.

**Comment by BrunoBSM** [comment]
When you say "mujoco env" do you mean the gym env or your own simulation? like a MjSim()

**Comment by machinaut** [comment]
We have a couple small examples in the repository here, a few of which do render (so you can see how those files render images)

This repository is just python wrapper to the Mujoco library, if you want to understand how the mujoco library works then I would recommend looking at the documentation here http://www.mujoco.org/book/index.html

The pose of everything in the simulator is controlled by the `qpos` variable -- if you set that, then you need to make sure its forward consistent, so following that by `mj_forward` will make sure variables are correct.  The `render` function is possibly what you want in order to render an image of the scene.
