### ISSUE TITLE
[Feature request]: Support for Mujoco 2.0

### ISSUE THREAD

**Issue by zuoxingdong** [openai/mujoco-py#303]

**Comment by gpzhaome** [comment]
I'm also wondering if Mujoco 2.0 will be supported.

**Comment by ogroth** [comment]
+1 on the feature request :)
MuJoCo 2.0 has quite a few useful features (simulation of non-rigid objects, semantic segmentation rendering of individual geoms).
Are there any plans to support the new MuJoCo version or is there even a timeline for a tentative release of mujoco-py 2.0?
Out of curiosity I've tried to wrap the new MuJoCo headers myself by pointing the [wrapper generator](https://github.com/openai/mujoco-py/blob/master/scripts/gen_wrappers.py) to the new files, but the new GUI APIs cause issues since the current wrapping script can't parse C union data structures which are used in the new headers.

**Comment by machinaut** [comment]
Right now we don't use it internally, and unfortunately the way bindings were released was very manual and took a lot time to get tests for everything we thought of (but the tests are by no means comprehensive).

Additionally, in the past when we've moved versions, we've found reinforcement learning benchmarks (performance of a trained policy, learning curves of an implementation, etc) change.

However the improved speed is a pretty compelling reason to consider the upgrade.

Inspired individuals are encouraged to look at the `pxd` files, which (although they look like they were autogenerated from headers, it was actually sadly manual) need updating https://github.com/openai/mujoco-py/tree/master/mujoco_py/pxd

I took a quick stab at the update and there were enough changes to header file and struct definitions that all the interfaces are backwards-incompatible (probably why it went from a `1.x` release to a `2.x` release).

The interface changes in the release notes look like it shouldn't be too much work to make a new version -- but since this is incompatible, I think the real question is about whether/when to support this release, and whether to support multiple releases or deprecate the 1.50 series.

release notes https://www.roboti.us/index.html#mujoco200

cc: @jonasschneider

**Comment by zuoxingdong** [comment]
@machinaut some news recently regarding upgrading ?

**Comment by hyc6668378** [comment]
please update to Mujoco_py 2.0.
I can't wait any more...

**Comment by kracon7** [comment]
Also wondering if there's any timeline on support for mujoco2.0.
Really appreciate it.

**Comment by Ziyu-Ji** [comment]
Same here. I'm working on non-rigid object. Need it so bad.

**Comment by MillionIntegrals** [comment]
You can check out #368, should be merged relatively soon.

**Comment by MillionIntegrals** [comment]
This is done now. Just released a version 2.0.2.0a1.
