### ISSUE TITLE
Environment changed, not working for python2 anymore

### ISSUE THREAD

**Issue by hmishra2250** [openai/mujoco-py#45]
In setup.py,  the first line 

> import importlib.util

This works only with python3! Also as mentioned in the installation guide, the eggs are not available through pip. I had to install using git (which failed of course!).

**Comment by hmishra2250** [comment]
I just saw .python-version file which mentions python 3.5.2. Is there someway I can use it with python2? I am stuck cuz I was reading and working old source code, but this one seems way more organized. 

Thanks

**Comment by jonasschneider** [comment]
Python 2 is not supported since the (just released) 1.50.1.x series.

You can keep using the [`0.5` branch](https://github.com/openai/mujoco-py/tree/0.5); the latest release is [`0.5.7`](https://github.com/openai/mujoco-py/releases/tag/0.5.7) which you can install with `pip install mujoco-py==0.5.7`.

Sorry for the inconvenience!
