### ISSUE TITLE
Some confusion about variables and functions in mujoco-py

### ISSUE THREAD

**Issue by zichunxx** [openai/mujoco-py#768]
Hi!

I am working on gym robotics env and learning how to use mujoco. 

When I browse [fetch_env.py](https://github.com/openai/gym/blob/c33cfd8b2cc8cac6c346bc2182cd568ef33b8821/gym/envs/robotics/fetch_env.py), I have a question about the following code snippet:

```
grip_pos = self.sim.data.get_site_xpos('robot0:grip')

dt = self.sim.nsubsteps * self.sim.model.opt.timestep

grip_velp = self.sim.data.get_site_xvelp('robot0:grip') * dt
```

Which kind of velocity is acquired by `get_site_xvelp` and `get_site_xvelr`, respectively?

Besides, what do `sim.nsubsteps` and `sim.model.opt.timestep` imply? Are these variables related to `frame_skip`? How do these variables affect the Mujoco control?

I found some relevant issues (e.g., [1345](https://github.com/openai/gym/issues/1345#issue-416401805) and [255](https://github.com/openai/mujoco-py/issues/255#issue-322583881)), but it seems that they were not answered in a clear and understandable way.

Thanks in advance!

**Comment by rob-x-ai** [comment]
Hi there!

I can see that you're curious about the role of certain variables and functions in the fetch_env.py code snippet you've shared. Let me break it down for you in a more conversational manner.

So, when you see get_site_xvelp and get_site_xvelr, they're actually fetching the linear and angular velocities for a specific site, which in this case is the gripper site ('robot0:grip'). The difference between them is that get_site_xvelp gives you linear velocity, while get_site_xvelr gives you angular velocity.

Now, about sim.nsubsteps and sim.model.opt.timestep, you're right! They are indeed related to frame skip and play a role in how Mujoco control works.

sim.nsubsteps is the number of substeps that the simulation runs during each step, which helps in achieving better simulation accuracy and stability. On the other hand, sim.model.opt.timestep represents the duration of one time step in the Mujoco physics simulation.

The product of these two variables, dt = self.sim.nsubsteps * self.sim.model.opt.timestep, is used to scale the velocities to match the units of the position variables. This is super important for the agent to understand the environment and learn effectively.

I hope that clears things up! Feel free to reach out if you have more questions or need any further explanations. Happy coding!

**Comment by zichunxx** [comment]
You are so nice!

Thanks to your explanation, I have understood the definitions of `get_site_xvelp` and `get_site_xvelr`.

However, I'm still confused about 

> Now, about sim.nsubsteps and sim.model.opt.timestep, you're right! They are indeed related to frame skip and play a role in how Mujoco control works.

(1) Could you please explain `sim.nsubsteps` and `sim.model.opt.timestep` more specifically? 

(2) Should I call `sim.step()` under each `sim.model.opt.timestep` or `dt`? Any why?

(3) Besides, how is `dt = self.sim.nsubsteps * self.sim.model.opt.timestep` used to scale the velocities to match the units of position variables? 

In [this line](https://github.com/openai/gym/blob/c33cfd8b2cc8cac6c346bc2182cd568ef33b8821/gym/envs/robotics/fetch_env.py#L91), the position velocity of the gripper is obtained by `self.sim.data.get_site_xvelp('robot0:grip') * dt`. Is it actually a variation of position in  `dt`?

Thanks!

**Comment by rob-x-ai** [comment]
Glad my previous explanations were helpful! I'm more than happy to address your remaining questions:

1) About `sim.nsubsteps` and `sim.model.opt.timestep`:
- `sim.nsubsteps`: This variable specifies the number of simulation steps executed for each call to the environment's `step()` function. A larger number of substeps leads to a more accurate simulation but may require more computational resources.
- `sim.model.opt.timestep`: This variable represents the duration of a single timestep in the simulation, typically expressed in seconds. It defines the granularity of the simulation process and serves as the fundamental time unit.

2) When to call `sim.step()`:
You only need to call `sim.step()` once for each `sim.model.opt.timestep`. This is because `sim.step()` advances the simulation by one timestep. Internally, the environment takes care of calling `sim.step()` for the required number of substeps (as specified by `sim.nsubsteps`) within its `step()` function, so you don't need to worry about calling it multiple times yourself.

3) Scaling velocities using `dt`:
`dt` represents the total duration of all substeps, which is calculated as `self.sim.nsubsteps * self.sim.model.opt.timestep`. Since position variables in Mujoco are given in meters and velocities from `get_site_xvelp()` are in meters per second, you need to multiply the velocity by the time duration (`dt`) to obtain the position change (displacement).

Also in the line `grip_velp = self.sim.data.get_site_xvelp('robot0:grip') * dt`, the displacement of the gripper during the total duration of all substeps (`dt`) is calculated by multiplying its linear velocity by `dt`. This gives you the amount by which the position of the gripper has changed during that time, taking into account all intermediate simulation steps.

I hope this clears up any remaining confusion.

**Comment by zichunxx** [comment]
Easy to understand, you made my day!

Hopefully, such novice friendly answers can be added to the official documentation.

In addition to the official documentation, are there any recommended sources for diving into Mujoco and Mujoco-py?

**Comment by rob-x-ai** [comment]
Hey,

Resources to help you learn more about Mujoco and mujoco-py:

1. Tutorials and Guides:
   - OpenAI Spinning Up: https://spinningup.openai.com/en/latest/index.html
   - Robosuite, a Mujoco-based toolkit: https://robosuite.ai/docs/overview.html

2. YouTube Videos:
   - https://www.youtube.com/results?search_query=MuJoCo+Physics+Engine+Overview%3A
   
   
Enjoy! 😉

**Comment by zichunxx** [comment]
Much appreciated!
